### ISSUE TITLE
Liste già aperte

### ISSUE THREAD

**Issue by amerlo94** [mstn/awesome-coronavirus-italia#2]
Al fine di non duplicare le informazioni, non conviene collaborare in altre liste già presenti. Questa la migliore che ho trovato?

https://github.com/soroushchehresa/awesome-coronavirus

Altrimenti si può prendere quella come esempio e farne una italiana (awesome-coronavirus-italy) con la medesima struttura.

**Comment by mstn** [comment]
Hai ragione. Ottimo il link che hai trovato!

Lo scopo di questa lista è indicare le risorse nazionali e le informazioni pratiche (in Italiano) di interesse per la gente comune (es dove fare la spesa). Quindi non la vedo come un duplicato di quella internazionale.

Devo scriverlo da qualche parte però!

Che ne dici se cambio il nome come suggerisci (mi sembrava brutto mettere awesome vicino a coronavirus, ma se lo fanno gli altri è ok) e ti aggiungo ai collaboratori?

**Comment by amerlo94** [comment]
Penso anche io che una lista italiana abbia la sua utilità. Quindi cambierei nome e proverei ad adottare la medesima struttura.

**Comment by mstn** [comment]
TI ho aggiunto come collaboratore, così puoi modificare senza fare PR.

Aggiungo  il link sopra alla lista.
